name: Pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Sync uv
        run: uv sync --locked --all-extras --dev
      - uses: pre-commit/action@v3.0.1
